language: node_js
sudo: required
node_js:
  - 9.5.0
jdk:
  - oraclejdk8
services:
  - neo4j
before_install:
  # Install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-3.2.2-unix.tar.gz
  - tar -xzf neo4j-community-3.2.2-unix.tar.gz
  - neo4j-community-3.2.2/bin/neo4j start
  # HACK need to change the password initially; changing it and then reverting:
  - sleep 10  # give Neo4J some time to start
  - curl -v POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=test"
  - curl -v POST http://neo4j:neo4j2@localhost:7474/user/neo4j/password -d"password=test2"
script:
  - npm install
  - npm test

#after_success: npm run coverage
