dist: trusty
language: node_js
sudo: required
node_js:
  - 9.5.0
jdk:
  - openjdk8
services:
  - neo4j
env:
    global:
      URL=URL EDAMAM_URL=EDAMAMURL EDAMAM_APP_KEY=EDAMAMAPPKEY EDAMAM_APP_ID=EDAMAMAPPID TESCO_PRIMARY_KEY=TESCOPRIMARYKEY SPOONACULAR_URL=SPOONACULARURL SPOONACULAR_KEY=SPOONACULARKEY
script:
  - npm install
  - npm test

#after_success: npm run coverage