dist: trusty
language: node_js
sudo: required
node_js:
  - 9.5.0
jdk:
  - openjdk8
services:
  - neo4j
script:
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
