var config = {};
config.url = "http://username:password@localhost:7474/db/data/transaction/commit/";
config.edamam_url = "https://api.edamam.com/api/nutrition-data";
config.edamam_app_key = "";
config.edamam_app_id = "";
config.tesco_primary_key = "";
config.spoonacular_url = "https://api.spoonacular.com/recipes/random";
config.spoonacular_key = "";
module.exports = config;
